# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cloudinarySettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cloudinarySettingsDialog(object):
    def setupUi(self, cloudinarySettingsDialog):
        cloudinarySettingsDialog.setObjectName("cloudinarySettingsDialog")
        cloudinarySettingsDialog.resize(406, 483)
        self.buttonBox = QtWidgets.QDialogButtonBox(cloudinarySettingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(90, 420, 241, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton = QtWidgets.QPushButton(cloudinarySettingsDialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 40, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.logFile_path = QtWidgets.QLabel(cloudinarySettingsDialog)
        self.logFile_path.setGeometry(QtCore.QRect(30, 70, 321, 31))
        self.logFile_path.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.logFile_path.setWordWrap(True)
        self.logFile_path.setObjectName("logFile_path")
        self.label_2 = QtWidgets.QLabel(cloudinarySettingsDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(cloudinarySettingsDialog)
        self.label_3.setGeometry(QtCore.QRect(30, 180, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(cloudinarySettingsDialog)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 121, 16))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(cloudinarySettingsDialog)
        self.label.setGeometry(QtCore.QRect(30, 320, 91, 31))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(cloudinarySettingsDialog)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 350, 51, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.maxSizeLineEdit = QtWidgets.QLineEdit(cloudinarySettingsDialog)
        self.maxSizeLineEdit.setGeometry(QtCore.QRect(30, 350, 71, 20))
        self.maxSizeLineEdit.setObjectName("maxSizeLineEdit")
        self.cloudName_text = QtWidgets.QLineEdit(cloudinarySettingsDialog)
        self.cloudName_text.setGeometry(QtCore.QRect(30, 150, 301, 20))
        self.cloudName_text.setObjectName("cloudName_text")
        self.apiKey_text = QtWidgets.QLineEdit(cloudinarySettingsDialog)
        self.apiKey_text.setGeometry(QtCore.QRect(30, 200, 301, 20))
        self.apiKey_text.setObjectName("apiKey_text")
        self.apiSecret_text = QtWidgets.QLineEdit(cloudinarySettingsDialog)
        self.apiSecret_text.setGeometry(QtCore.QRect(30, 250, 301, 20))
        self.apiSecret_text.setObjectName("apiSecret_text")
        self.label_5 = QtWidgets.QLabel(cloudinarySettingsDialog)
        self.label_5.setGeometry(QtCore.QRect(110, 350, 21, 16))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(cloudinarySettingsDialog)
        self.buttonBox.accepted.connect(cloudinarySettingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(cloudinarySettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(cloudinarySettingsDialog)

    def retranslateUi(self, cloudinarySettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        cloudinarySettingsDialog.setWindowTitle(_translate("cloudinarySettingsDialog", "Settings"))
        self.pushButton.setText(_translate("cloudinarySettingsDialog", "Log Folder.."))
        self.logFile_path.setText(_translate("cloudinarySettingsDialog", "TextLabel dasdasd asd asjdioada dsadiojao das dasd asdsa ada sdasdsdasdasdasd dasdaijo"))
        self.label_2.setText(_translate("cloudinarySettingsDialog", "Cloud Name"))
        self.label_3.setText(_translate("cloudinarySettingsDialog", "API Key"))
        self.label_4.setText(_translate("cloudinarySettingsDialog", "API Secret"))
        self.label.setText(_translate("cloudinarySettingsDialog", "Max Size"))
        self.pushButton_2.setText(_translate("cloudinarySettingsDialog", "Set.."))
        self.label_5.setText(_translate("cloudinarySettingsDialog", "Mb"))
