# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tagManagerDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tagManagerDialog(object):
    def setupUi(self, tagManagerDialog):
        tagManagerDialog.setObjectName("tagManagerDialog")
        tagManagerDialog.resize(903, 778)
        self.verticalLayout = QtWidgets.QVBoxLayout(tagManagerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tagsList = QtWidgets.QListWidget(tagManagerDialog)
        self.tagsList.setObjectName("tagsList")
        self.gridLayout.addWidget(self.tagsList, 1, 2, 1, 2)
        self.streetInput = QtWidgets.QPlainTextEdit(tagManagerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.streetInput.sizePolicy().hasHeightForWidth())
        self.streetInput.setSizePolicy(sizePolicy)
        self.streetInput.setMaximumSize(QtCore.QSize(16777215, 50))
        self.streetInput.setObjectName("streetInput")
        self.gridLayout.addWidget(self.streetInput, 0, 1, 1, 1)
        self.tagsInput = QtWidgets.QPlainTextEdit(tagManagerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagsInput.sizePolicy().hasHeightForWidth())
        self.tagsInput.setSizePolicy(sizePolicy)
        self.tagsInput.setMaximumSize(QtCore.QSize(16777215, 50))
        self.tagsInput.setObjectName("tagsInput")
        self.gridLayout.addWidget(self.tagsInput, 0, 2, 1, 1)
        self.streetList = QtWidgets.QListWidget(tagManagerDialog)
        self.streetList.setObjectName("streetList")
        self.gridLayout.addWidget(self.streetList, 1, 1, 1, 1)
        self.businessList = QtWidgets.QListWidget(tagManagerDialog)
        self.businessList.setObjectName("businessList")
        self.gridLayout.addWidget(self.businessList, 1, 0, 1, 1)
        self.businessInput = QtWidgets.QPlainTextEdit(tagManagerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.businessInput.sizePolicy().hasHeightForWidth())
        self.businessInput.setSizePolicy(sizePolicy)
        self.businessInput.setMaximumSize(QtCore.QSize(16777215, 50))
        self.businessInput.setObjectName("businessInput")
        self.gridLayout.addWidget(self.businessInput, 0, 0, 1, 1)
        self.openAddKeywordDialogButton = QtWidgets.QPushButton(tagManagerDialog)
        self.openAddKeywordDialogButton.setMaximumSize(QtCore.QSize(16777206, 16777215))
        self.openAddKeywordDialogButton.setObjectName("openAddKeywordDialogButton")
        self.gridLayout.addWidget(self.openAddKeywordDialogButton, 0, 3, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(tagManagerDialog)
        QtCore.QMetaObject.connectSlotsByName(tagManagerDialog)

    def retranslateUi(self, tagManagerDialog):
        _translate = QtCore.QCoreApplication.translate
        tagManagerDialog.setWindowTitle(_translate("tagManagerDialog", "Tag Manager"))
        self.tagsList.setSortingEnabled(True)
        self.streetInput.setPlaceholderText(_translate("tagManagerDialog", "Search street name..."))
        self.tagsInput.setPlaceholderText(_translate("tagManagerDialog", "Search tags..."))
        self.streetList.setSortingEnabled(True)
        self.businessList.setSortingEnabled(True)
        self.businessInput.setPlaceholderText(_translate("tagManagerDialog", "Search businesses..."))
        self.openAddKeywordDialogButton.setText(_translate("tagManagerDialog", "+"))
